"use client";

import dynamic from "next/dynamic";
import type { ComponentType } from "react";

// Each demo is its own chunk. /lab/[slug] is one route for every component,
// so a static import would bundle all of them into every page; dynamic()
// splits them and the page only loads the demo it renders.
const demos: Record<string, ComponentType> = {
  odometer: dynamic(() => import("./components/odometer")),
  "hold-to-delete": dynamic(() => import("./components/hold-to-delete")),
  "segmented-control": dynamic(() => import("./components/segmented-control")),
  "tilt-card": dynamic(() => import("./components/tilt-card")),
  dock: dynamic(() => import("./components/dock")),
  sheet: dynamic(() => import("./components/sheet")),
  "toast-stack": dynamic(() => import("./components/toast-stack")),
  "elastic-slider": dynamic(() => import("./components/elastic-slider")),
  "magnetic-button": dynamic(() => import("./components/magnetic-button")),
  "text-scramble": dynamic(() => import("./components/text-scramble")),
  "swipe-deck": dynamic(() => import("./components/swipe-deck")),
  "scroll-reveal": dynamic(() => import("./components/scroll-reveal")),
  "copy-button": dynamic(() => import("./components/copy-button")),
  "expanding-search": dynamic(() => import("./components/expanding-search")),
  accordion: dynamic(() => import("./components/accordion")),
  "expanding-card": dynamic(() => import("./components/expanding-card")),
  "otp-input": dynamic(() => import("./components/otp-input")),
  "toggle-switch": dynamic(() => import("./components/toggle-switch")),
  "command-palette": dynamic(() => import("./components/command-palette")),
  marquee: dynamic(() => import("./components/marquee")),
  "reorder-list": dynamic(() => import("./components/reorder-list")),
  "compare-slider": dynamic(() => import("./components/compare-slider")),
  "multi-step-form": dynamic(() => import("./components/multi-step-form")),
  "upload-button": dynamic(() => import("./components/upload-button")),
  "tooltip-group": dynamic(() => import("./components/tooltip-group")),
  "dropdown-menu": dynamic(() => import("./components/dropdown-menu")),
  "dynamic-island": dynamic(() => import("./components/dynamic-island")),
  "scrub-input": dynamic(() => import("./components/scrub-input")),
  "star-rating": dynamic(() => import("./components/star-rating")),
  "like-button": dynamic(() => import("./components/like-button")),
  "sliding-tabs": dynamic(() => import("./components/sliding-tabs")),
  "page-dots": dynamic(() => import("./components/page-dots")),
  "collapsible-sidebar": dynamic(() => import("./components/collapsible-sidebar")),
  "snap-carousel": dynamic(() => import("./components/snap-carousel")),
  "skeleton-loader": dynamic(() => import("./components/skeleton-loader")),
  "context-menu": dynamic(() => import("./components/context-menu")),
  "notification-bell": dynamic(() => import("./components/notification-bell")),
  "avatar-stack": dynamic(() => import("./components/avatar-stack")),
  "morphing-button": dynamic(() => import("./components/morphing-button")),
  "kanban-board": dynamic(() => import("./components/kanban-board")),
  "color-swatches": dynamic(() => import("./components/color-swatches")),
  "mini-calendar": dynamic(() => import("./components/mini-calendar")),
  "floating-label": dynamic(() => import("./components/floating-label")),
  "password-field": dynamic(() => import("./components/password-field")),
  "filter-list": dynamic(() => import("./components/filter-list")),
  "gauge": dynamic(() => import("./components/gauge")),
  "sparkline": dynamic(() => import("./components/sparkline")),
  "bar-chart": dynamic(() => import("./components/bar-chart")),
  "stacked-drawer": dynamic(() => import("./components/stacked-drawer")),
  "confetti-button": dynamic(() => import("./components/confetti-button")),
  "typewriter": dynamic(() => import("./components/typewriter")),
  "tag-input": dynamic(() => import("./components/tag-input")),
  "range-slider": dynamic(() => import("./components/range-slider")),
  "number-stepper": dynamic(() => import("./components/number-stepper")),
  "select-menu": dynamic(() => import("./components/select-menu")),
  "undo-toast": dynamic(() => import("./components/undo-toast")),
  "file-dropzone": dynamic(() => import("./components/file-dropzone")),
  "chat-thread": dynamic(() => import("./components/chat-thread")),
  "loader-set": dynamic(() => import("./components/loader-set")),
  "wheel-picker": dynamic(() => import("./components/wheel-picker")),
  "slide-to-confirm": dynamic(() => import("./components/slide-to-confirm")),
  "pull-to-refresh": dynamic(() => import("./components/pull-to-refresh")),
  "hover-card": dynamic(() => import("./components/hover-card")),
  "tree-view": dynamic(() => import("./components/tree-view")),
  "pricing-toggle": dynamic(() => import("./components/pricing-toggle")),
  "reading-progress": dynamic(() => import("./components/reading-progress")),
  "code-block": dynamic(() => import("./components/code-block")),
  "wave-text": dynamic(() => import("./components/wave-text")),
  "dot-grid": dynamic(() => import("./components/dot-grid")),
  "spotlight-card": dynamic(() => import("./components/spotlight-card")),
  "story-progress": dynamic(() => import("./components/story-progress")),
  // new-component:entries
};

export function LabDemo({ slug }: { slug: string }) {
  const Demo = demos[slug];
  return Demo ? <Demo /> : null;
}
